theme: jekyll-theme-minimal
title: International Association of Geodesy
logo: IAG.png
description: Severine Rosat, University of Strasbourg and CNRS & Xiaoming Cui, Chinese Academy of Sciences, chair and co-chair of Sub-Commission SC 3.1 Earth Tides and Geodynamics, International Association of Geodesy (IAG)
