theme: jekyll-theme-minimal
title: International Association of Geodesy
logo: IAG.png
description: Severine Rosat, University of Strasbourg and CNRS 
& Xiaoming Cui, Chinese Academy of Sciences, 
chair and co-chair
