theme: jekyll-theme-minimal
title: International Association of Geodesy
#logo: IAG.png
author: Severine Rosat
description: Severine Rosat (University of Strasbourg and CNRS, France) & Xiaoming Cui (Chinese Academy of Sciences, China), chair and co-chair
