#remote_theme: pages-themes/architect@v0.2.0
#remote_theme: pages-themes/dinky@v0.2.0
#remote_theme: pages-themes/midnight@v0.2.0
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme
#theme: jekyll-theme-minimal
title: Sub-Commission 3.1 Earth Tides and Geodynamics
#logo: IAG.png
author: Severine Rosat
description: Severine Rosat (University of Strasbourg and CNRS, France) & Xiaoming Cui (Chinese Academy of Sciences, China), chair & co-chair
