#remote_theme: pages-themes/architect@v0.2.0
remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme
#theme: jekyll-theme-minimal
title: International Association of Geodesy
#logo: IAG.png
author: Severine Rosat
description: Severine Rosat (University of Strasbourg and CNRS, France) & Xiaoming Cui (Chinese Academy of Sciences, China), chair & co-chair
