theme: jekyll-theme-minimal
title: International Association of Geodesy
logo: IAG.png
description: Carla Braitenberg, University of Trieste & Severine Rosat, University of Strasbourg and CNRS, 
_Chair and co-chair of Sub-Commission SC 3.1 Earth Tides and Geodynamics, International Association of Geodesy (IAG)_
