baseURL = "http://iag-sc31.github.io/"
languageCode = "en-us"
title = "IAG SC3.1"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
author= "Séverine Rosat (France) & Xiaoming Cui (China), chair & co-chair"

[services]
  [services.disqus]
    shortname = ''
  [services.instagram]
    accessToken = ''
    disableInlineCSS = false
  [services.rss]
    limit = -1
  [services.twitter]
    disableInlineCSS = false


[params]
    author = "Severine Rosat"
    description = "Sub-Commission 3.1 webpages"
    githubUsername = "iag-sc31"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    keywords = "Geodesy, Time-varying Gravimetry, GRACE, GRACE-FO, InSAR, GNSS, cold-atom gravimetry"

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/Online seminars/"
    name = "Posts"
    weight = 3

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:me@example.com"
    name = "fas fa-envelope"
    weight = 1

[[menu.icon]]
    url = "https://github.com/username/"
    name = "fab fa-github"
    weight = 2

[[menu.icon]]
    url = "https://twitter.com/username/"
    name = "fab fa-twitter"
    weight = 3

[[menu.icon]]
    url = "https://www.linkedin.com/in/username/"
    name = "fab fa-linkedin"
    weight = 4

[[menu.icon]]
    url = "https://www.stackoverflow.com/username/"
    name = "fab fa-stack-overflow"
    weight = 5
